DROP TABLE IF EXISTS produto;

CREATE TABLE produto (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nome VARCHAR(100) NOT NULL,
                         descricao VARCHAR(255),
                         preco DECIMAL(10, 2) NOT NULL
);